name: Build & Test CI

on:
  push:
    branches: [master, dev]

  pull_request:
    branches:
      - master
      - dev

defaults:
  run:
    working-directory: omui
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
            
      - name: Install dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Lint & Format
        run: yarn run lint && yarn run format
        
      - name: Build
        run: yarn build
        
      # - name: Run all tests
      #   run: yarn test   
